version: '3.4'
services:
  db:
    image: wiliands/mysql-curso-springboot
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: springboot
    ports:
      - "3306:3306"
    networks:
      - udemy-network
  curso-springboot:
    image: wiliands/curso-springboot
    restart: always
    build: ./CursoSpringBoot
    working_dir: /CursoSpringBoot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./CursoSpringBoot:/CursoSpringBoot
      - /home/wilian/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge
